# Generated by Django 4.1.3 on 2022-12-03 12:25

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studinfo',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studinfo',
            name='date_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='studinfo',
            name='created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 12, 3, 17, 55, 32, 820142)),
        ),
    ]
